### ISSUE TITLE
There is no possible way of resetting the gyro sensor to 0

### ISSUE THREAD

**Issue by Jensonbruins** [simonedegiacomi/EV3-API#11]

**Comment by simonedegiacomi** [comment]
Hi!
Are you using the develop branch?
It's true that in master you cannot reset the changes, but this is a fork of the library, with the changes in the develop branch. You should be able to call the [ResetEV3GyroSensor](https://github.com/simonedegiacomi/EV3-API/blob/805a0b64048f53e77419997c3a03ce8d5f60fbc1/src/ev3_sensors/ev3_gyro.h#L21)

**Comment by simonedegiacomi** [comment]
I close this issue since I saw that you create the issue on the original repository.

Link to the new issue: https://github.com/c4ev3/EV3-API/issues/25
